const USER_SUBMIT = 'USER_SUBMIT';
const WALLET_REQUEST = 'WALLET_REQUEST';
const WALLET_RESPONSE = 'WALLET_RESPONSE';
const WALLET_SUBMIT = 'WALLET_SUBMIT';
const DELETE_TABLE_DATA = 'DELETE_TABLE_DATA';

export { USER_SUBMIT, WALLET_SUBMIT, WALLET_REQUEST, WALLET_RESPONSE, DELETE_TABLE_DATA };
