const USER_SUBMIT = 'USER_SUBMIT';
const WALLET_REQUEST = 'WALLET_REQUEST';
const WALLET_RESPONSE = 'WALLET_RESPONSE';
const WALLET_SUBMIT = 'WALLET_SUBMIT';

export { USER_SUBMIT, WALLET_SUBMIT, WALLET_REQUEST, WALLET_RESPONSE };
